apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-service
  name: gateway-service
  namespace: dev-javagrunt-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: dashaun/com.javagrunt.service.gateway:v0.0.23
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ZIPKIN_ENDPOINT
              value: http://openzipkin.dev-javagrunt-com.svc.cluster.local:9411/api/v2/spans
          envFrom:
            - secretRef:
                name: redis-cloud
---

apiVersion: v1
kind: Service
metadata:
  name:  gateway-service
  namespace: dev-javagrunt-com
spec:
  selector:
    app:  gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: grpc  
