apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pulsar-service
  namespace: javagrunt-com
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/window: "60s"
    spec:
      containers:
        - image: dashaun/com.javagrunt.service.pulsar:v0.0.1
          env:
            - name: ZIPKIN_ENDPOINT
              value: http://openzipkin.javagrunt-com.svc.cluster.local:9411/api/v2/spans
