apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: youtube-listener
  namespace: javagrunt-com
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "1"
        autoscaling.knative.dev/window: "900s"
    spec:
      containers:
        - image: dashaun/com.javagrunt.listener.youtube:v0.0.3