apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-service
  name: hello-service
  namespace: dev-javagrunt-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
        - name: hello-service
          image: dashaun/com.javagrunt.service.hello:v0.0.31
          ports:
            - containerPort: 8080
              name: http

---

apiVersion: v1
kind: Service
metadata:
  name:  hello-service
  namespace: dev-javagrunt-com
spec:
  selector:
    app:  hello-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: hello-service
  namespace: dev-javagrunt-com
spec:
  advanced:
    restoreToOriginalReplicaCount: true
  scaleTargetRef:
    name: hello-service
  pollingInterval:  1
  cooldownPeriod:   3
  minReplicaCount:  0
  maxReplicaCount:  3
  triggers:
    - type: external
      metadata:
        scalerAddress: gateway-service.dev-javagrunt-com:9090
        threshold: "2"      