apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: youtube-listener
  name: youtube-listener
  namespace: dev-javagrunt-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-listener
  template:
    metadata:
      labels:
        app: youtube-listener
    spec:
      containers:
        - name: youtube-listener
          image: dashaun/com.javagrunt.listener.youtube:v0.0.10
          ports:
            - containerPort: 8080
              name: http

---

apiVersion: v1
kind: Service
metadata:
  name:  youtube-listener
  namespace: dev-javagrunt-com
spec:
  selector:
    app:  youtube-listener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: youtube-listener
  namespace: dev-javagrunt-com
spec:
  advanced:
    restoreToOriginalReplicaCount: true
  scaleTargetRef:
    name: youtube-listener
  pollingInterval:  1
  cooldownPeriod:   3
  minReplicaCount:  0
  maxReplicaCount:  3
  triggers:
    - type: external
      metadata:
        scalerAddress: gateway-service.dev-javagrunt-com:9090
        name: "youtube-listener"
        namespace: "dev-javagrunt-com"
        threshold: "1"      