apiVersion: batch/v1
kind: CronJob
metadata:
  name: youtube-task
  namespace: javagrunt-com
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: youtube-task
              image: dashaun/com.javagrunt.task.youtube:v0.0.2
              imagePullPolicy: IfNotPresent
              envFrom:
              - secretRef:
                  name: yugabyte-cloud
          restartPolicy: OnFailure