apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: youtube-listener
  namespace: javagrunt-com
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/activation-scale: "3"
        autoscaling.knative.dev/max-scale: "10"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/window: "30s"
    spec:
      containers:
        - image: dashaun/com.javagrunt.listener.youtube:v0.0.3