apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-native-pi
  name: spring-boot-native-pi
  namespace: javagrunt-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-native-pi
  template:
    metadata:
      labels:
        app: spring-boot-native-pi
    spec:
      containers:
        - name: spring-boot-native-pi
          image: dashaun/spring-boot-native-pi-default:latest
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http

---

apiVersion: v1
kind: Service
metadata:
  name:  spring-boot-native-pi
spec:
  selector:
    app:  spring-boot-native-pi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080